[package]
name = "yew-test"
version = "0.1.0"
authors = ["Stig Johan Berggren <stigjb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
yew = { version="0.14.3", features=["web_sys"] }
wasm-bindgen = "0.2.60"
